### ISSUE TITLE
Editing Teams

### ISSUE THREAD

**Issue by taltaub22** [FirstLegoLeagueIL/fllscoring#57]
"Any editing in a field on Teams sheet takes focus out of the field, and jumps to top of list.
This effectively makes editing impossible"

This haapnes because the code is watching for changes and when it sees a change it saves by reloading the temas.
This is written in the code: "TODO: this is a performance killer as it rebuilds the entire page on every save"

I see that we have 3 options:
1. Creating a save button at the bottom of the page - I think that the more logical solution, if we don't want to change the saving process. When one finish editing he press save.
2. Checking inside the watch for changed to only save when an input is blur (not in focus). - This is a problem because is will still take you to the top of the page when saving.
3. Changing the saving procces to not refresh the page when saving.

@yosikarl @alanggreen @ThinkRedstone @idanstark42 @itamargreen

**Comment by alanggreen** [comment]
I suggest a two phase solution
1. Implement your 1st solution - most straightforward and probably the easiest to code.
2. Open this as an issue in FirstLegoLeague, and put the 3 options in Slack. Martin answers the slack channel very quickly, and will probably have ideas on what to do. If our solution is inline with his ideas, the merge into FirstLegoLeague will be much smoother.

**Comment by idanstark42** [comment]
I agree with Alan. That seems like the right cider of action

**Comment by idanstark42** [comment]
Also assigning this to @itamargreen because he has the time to implement the solution
