### ISSUE TITLE
Editing team data does not update it in other pages

### ISSUE THREAD

**Issue by taltaub22** [FirstLegoLeagueIL/fllscoring#58]
"Editing a field in Teams list does not always update scorekeeping table.
In our example, we had
String String - 123
We removed 123 and it got updated
We removed the -, it did not get updated"

When I got to reproduce the bug, the scorekeeping table did not update at all when i edited the team name.
This is caused because the controllers are all loaded when the app is loaded and that it. When we re enter a tab, the data does not refresh.
The problem is more severe than just the team name in scorekeeping as no data (almost) is updated after the page is loaded. Just only when specified. 

Possible solutions:
1. On page change refresh the data on the page we got into.
2. Add a refresh button on the scorekeeping page.

note: some data is reloaded when a score is submitted

@alanggreen @yosikarl @idanstark42 @ThinkRedstone @itamargreen

**Comment by idanstark42** [comment]
It's not the users kin to sync this data. It's our. If we want to sync this data behind the scenes, we need to add a $watch in the scorekeeper view

**Comment by idanstark42** [comment]
I'm assigning @itamargreen to implement the solution @taltaub22 suggested, since @taltaub22 doesn't have the time to do it right now

**Comment by alanggreen** [comment]
Itamar looked at this. I'm going to ask him to discuss his solution with
Martin.

**Comment by idanstark42** [comment]
Solved
