### ISSUE TITLE
Support the notion of "current round" that will be default for new score entries

### ISSUE THREAD

**Issue by itamargreen** [FirstLegoLeagueIL/fllscoring#79]
similar to how table and referee are automatically filled in, the round and stage will also be filled in, according to some "current round&stage" record.

there are a few solutions, as far as I can see:

1. add to the `settings` angular service a `currentStage` property, which starts out as the first stage configured (usually "practice"). 

after entering the team number in the scoresheet page, the round & stage automatically gets filled in with the first round in `currentStage` in which the team doesn't have a score.

as soon as a scoresheet with a stage **after the `currentStage`** is submitted, `currentStage` changes to match that, and then is sent through mhub so that other devices also have the new stage as the `currentStage`.

2. completely manual: settings has a `currentStage` and `currentRound`, and those are changed manually in the settings as the tournament progresses.

**Comment by alanggreen** [comment]
I prefer that the stage is not advanced automatically. 

Sometimes there is no break between the various rounds, and so some referees could still be submitting scores from the previous stage, while others are already submitting for the 1st round of the new stage . Yes, that has happened when a team argues a  log. 
So it's better for the head ref to change the stage  manually
